name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les commits vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest  # Spécifie l'environnement d'exécution

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Vérifie le code source de votre dépôt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configure Docker Buildx

      - name: Cache Docker layers
        uses: actions/cache@v3  # Caches les couches Docker pour accélérer les constructions
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Utilise l'action Docker Buildx pour construire et pousser l'image
        with:
          context: .  # Contexte de la construction Docker (répertoire actuel)
          push: true  # Pousse l'image vers GHCR
          tags: ghcr.io/arthurblanc/radarr_search:latest  # Tags de l'image
        env:
          DOCKER_BUILDKIT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilise le jeton GitHub pour l'authentification
