name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Update to the latest version

      - name: Cache Docker layers
        uses: actions/cache@v4  # Update to the latest version
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # Update to the latest version
        with:
          context: .
          push: true
          tags: ghcr.io/arthurblanc/radarr_search:latest
        env:
          DOCKER_BUILDKIT: 1
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
