name: radarr_search

on:
  push:
    branches:
      - main  # or your default branch
  # Optionally trigger on other events, like pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: radarr_search
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/ArthurBlanc/radarr_search:latest
        env:
          DOCKER_BUILDKIT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-created by GitHub for you
