name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Modifiez si nécessaire pour correspondre à votre branche par défaut

jobs:
  build:
    runs-on: ubuntu-latest  # Environnement d'exécution

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Vérifie le code source

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configure Docker Buildx

      - name: Cache Docker layers
        uses: actions/cache@v3  # Caches les couches Docker pour accélérer la construction
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Utilise l'action Docker Buildx pour construire et pousser l'image
        with:
          context: .  # Contexte de la construction Docker
          push: true  # Pousse l'image vers GHCR
          tags: ghcr.io/arthurblanc/radarr_search:latest  # Utilisez le nom d'utilisateur en minuscules
        env:
          DOCKER_BUILDKIT: 1
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}  # Utilisez le secret pour le jeton d'accès personnel
