name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4  # Ensure using the latest version

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2  # Latest stable version

      - name: 'Build and Push Docker Image'
        run: |
          docker build -t ghcr.io/arthurblanc/radarr_search:latest .
          docker push ghcr.io/arthurblanc/radarr_search:latest
